language: python

matrix:
  include:
  - python: 3.6
    sudo: required
  - python: 3.7
    sudo: required
    dist: xenial
  - python: 3.8
    sudo: required

services:
  - redis

compiler:
  - clang

sudo: false

cache: pip

install:
  - pip install -U wheel pypi setuptools --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt --upgrade
  - pip install git+https://github.com/nooperpudd/hiredis-py.git@master#egg=hiredis
  - pip check

script:
  - redis-server -v
  - pytest -v -s
  - py.test -v --cov=ttseries --cov-report xml
after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION

deploy:
  provider: pypi
  user: nooperpudd
  password:
    secure: zg529Q3C16zHwN+h/KdNJeXzLad8ibm8bGZojqCJgqB18UKk2tRDGoL5XpT+75gfdgUp1wbdaAgPuiSD0trK6nnwEto4IC9EnWI93cxSlHdDEfgjP61GclW3oF8nSjqfxo7LZRHtWhIiMcP5s5KBzfaGqlSZ8imSU2Jyh/0vj1VPYdMNQCKVrSeL5C6GGNI4ktvoE2ySNgCQZngGS6vZRuRIu2bRW4WHTbrpd1Hc/7S8Ub71Tvhpb8ZHBQDuEbUC1qQbVRYr0MrzhhVpBQqOeSyEMibVEl/N/bz/jeRqXN4FItbMeeZIrpHhagvJ6ksgF5T1YpwpXRpU2eurxd7WywUCAPyCUDmxP1qu/V6uWY6pVqzgrvYkzhq2FOgykc1xN5W7nonGHUyc3QHxVFdbb8k/xSf5ns3dXPQAOpPsXnd7ihHxpQqxd1fFlD3AZIzHg5emhpupdLI5c2+hZ7BEuRNlTU8uF//W9KdYnVxI34zvJKyKsXBg0r8SD5gYqFsaCAJodpDZOC6JE2tpx2+ERCeJV7iYQELyiJe8Oe2zV7nOrb2H+s644sfBhkwHA/0DPqIALhlcbk8neHMRwbNWMEM52kbC3EyX4On11AlLd+hS95bmmzrHH8i02ziLiTsnm0iAmja6I61D01kIGHmQpxBChfgpOQw/Q7YU+v6LmBA=
  distributions: sdist
  on:
    tags: true
    python: '3.6'
